### ISSUE TITLE
Move most files to a templates folder

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/project-generator#21]
Move most files to a templates folder

**Comment by PeterBowman** [comment]
Problem: superbuild-like repo teo-main instructs YCM to pull project-generator and configure it. But:

https://github.com/roboticslab-uc3m/project-generator/blob/ee9e5afc35b9d6c7ea872be979143bca50e568c4/CMakeLists.txt#L7-L8

The project-generator we fetch from GH is not configured, that is, the project-generator.sh script has not been run by the time we CMake-configure the project. The outcome of this process is an useless TemplateNameConfig.cmake export file. Of course, there is no way to install this on system.

**Comment by PeterBowman** [comment]
Not sure how to proceed, description says nothing. Also, I'm willing to remove project-generator from superbuilds and have it superseded by https://github.com/roboticslab-uc3m/project-generator/issues/23. Closing as invalid.

**Comment by jgvictores** [comment]
The main idea here was to have a more clear separation between:

1. The actual template files.
2. The project generator script and some installation logic (to install the script and the actual template files).

The proposal was to move (1) into a folder, just to make this separation more clear.

I understand that https://github.com/roboticslab-uc3m/project-generator/issues/23 renders this issue `invalid`, as (2) essentially ceases to exist - most (2) script/logic is directly on the GitHub side (maybe just some typical dot/config file?), so (1) tends to remain at the project root.

**Comment by PeterBowman** [comment]
Thank you for the insight. Speaking of template files, please note they're scattered around and hence cannot be grouped in a single location without altering the project structure, which needs to be preserved in order to make CMake configuration possible. By "template" I mean any file that contains "TEMPLATE_" either in its filename (see [cmake/*.cmake](https://github.com/roboticslab-uc3m/project-generator/tree/413c410f0eae31c537e386969492ca8035ee0b41/cmake)) or its contents (almost any [CMakeLists.txt](https://github.com/roboticslab-uc3m/project-generator/blob/413c410f0eae31c537e386969492ca8035ee0b41/libraries/ExampleLibrary/CMakeLists.txt)).
